import {
  FaHome,
  FaUser,
  FaCog,
  FaCircleNotch,
  FaFileAlt,
  FaVideo,
  FaFilePdf,
  FaGithub,
  FaTimes,
  FaStar,
  FaMoon,
  FaArrowLeft,
    FaPlusCircle,
  FaArrowRight,
  FaArrowCircleLeft,
  FaProjectDiagram,
  FaInfoCircle,
  FaEnvelope,
  FaToolbox,
  FaTasks,
  FaChevronCircleDown,
  FaCloud,
  FaChevronDown,
  FaChevronUp,
  FaChevronCircleUp,
  FaQuestionCircle,
  FaBars,
  FaArrowUp,
  FaArrowDown,
  FaGrinBeamSweat,
  FaSmile,
  FaWrench,
  FaTheRedYeti,
  FaLinkedin,
  FaCode,
  FaRegEnvelope,
  FaExpandAlt,
  FaSlidersH,
  FaCodeBranch,
  FaFile,
  FaHandSpock,
  FaExternalLinkAlt,
  FaSun,
  FaWalking,
  FaChessKnight,
  FaChess,
  FaDumbbell,
  FaFish,
  FaShareAlt,
  FaNewspaper,
  FaHandPointRight,
  FaAddressCard,
  FaTwitter,
  FaFacebook,
  FaReddit,
  FaColumns,
  FaAlignCenter,
  FaInfo,
  FaGraduationCap,
  FaMap,
  FaSkullCrossbones,
  FaAward,
  FaCheck,
  FaBan,
  FaTag,
  FaRegStar,
  FaRegMoon,
  FaRegFileAlt,
  FaAcquisitionsIncorporated,
  FaRegFile,
  // FaArrowRight,
  FaArrowCircleRight,
  FaRegCircle,
  FaCompress,
  FaPaperclip,
  FaCompressAlt,
  FaDirections,
  FaBriefcase,
} from "react-icons/fa";
import { FaP, FaPencil, FaSailboat } from "react-icons/fa6";

const getIcon = (iconName = "default") => {
  const iconMap = {
    home: <FaHome />,
    about: <FaInfoCircle />,
    user: <FaUser />,
    settings: <FaCog />,
    article: <FaRegFileAlt />, // Outline
    video: <FaVideo />,
    academic: <FaFilePdf />,
    code: <FaGithub />,
    projects: <FaWalking />,
    contact: <FaEnvelope />,
    mail: <FaRegEnvelope />,
    email: <FaRegEnvelope />,
    tools: <FaToolbox />,
    tasks: <FaTasks />,
    star: <FaRegStar />, // Outline star
    moon: <FaRegMoon />, // Outline moon
    close: <FaTimes />,
    cross: <FaBan />,
    return: <FaArrowLeft />,
    back: <FaArrowCircleLeft />,
    next: <FaArrowRight />,
    up: <FaArrowUp />,
    boat: <FaSailboat />,
    uparrow: <FaArrowUp />,
    down: <FaChevronDown />,
    downarrow: <FaArrowDown />,
    chevdown: <FaChevronCircleDown />,
    chevup: <FaChevronCircleUp />,
    overflow: <FaBars />,
    menu: <FaBars />,
    expand: <FaExpandAlt />,
    reduce: <FaCompressAlt />,
    file: <FaRegFile />, // Outline file
    github: <FaGithub />,
    linkedin: <FaLinkedin />,
    junk: <FaFish />,
    question: <FaQuestionCircle />,
    chess: <FaChessKnight />,
    catalogue: <FaWalking />,
    thesis: <FaProjectDiagram />,
    paper: <FaRegFile />, // Outline file
    complete: <FaNewspaper />,
    share: <FaShareAlt />,
    external: <FaExternalLinkAlt />,
    go: <FaHandPointRight />,
    twitter: <FaTwitter />,
    facebook: <FaFacebook />,
    reddit: <FaReddit />,
    sun: <FaSun />,
    columns: <FaColumns />,
    listview: <FaAlignCenter />,
    about: <FaInfo />,
    joke: <FaGrinBeamSweat />,
    smile: <FaSmile />,
    settings: <FaWrench />,
    yeti: <FaTheRedYeti />,
    school: <FaGraduationCap />,
    misc: <FaMap />,
    fail: <FaSkullCrossbones />,
    award: <FaAward />,
    grad: <FaGraduationCap />,
    editor: <FaPencil />,
    weather: <FaCloud />,
    tick: <FaCheck />,
    cross: <FaBan />,
    article: <FaPaperclip />,
    portfolio: <FaCode />,
    resume: <FaBriefcase />,
      plus: <FaPlusCircle />,
    tag: <FaTag />,
    rightarrow: <FaArrowCircleRight />,
    right: <FaArrowRight />,
    left: <FaArrowLeft />,
    dir: <FaDirections />,
  };

  return iconMap[iconName.toLowerCase()] || <FaAlignCenter />;
};

export default getIcon;
